resources:
  repositories:
    - repository: TIH-Pipelines
      type: git
      name: 'Enterprise Architecture/Pipelines'
      ref: 'refs/heads/feature/kongster'
    - repository: kongster
      type: git
      name: Synapse/Kong-Ingest


trigger:
  batch: true
  branches:
    include:
      - release/*
      - dev
      - master

pr:
  - master
  - release/*
  - dev

variables:
  - template: pipeline-vars.yml

  - name: projectImage
    value: '${{variables.teamName}}/${{variables.applicationName}}'
  - name: DeployPool
    value: 'Container Agents'
  - name: ACR_Service_Principal
    value: 'Azure DevOps Pipeline Service'
  - name: K8s-ServiceConnection-Dev
    value: Kubernetes_OnPrem_Dev_KubeConfig
  - name: K8s-ServiceConnection-SIT
    value: Kubernetes_OnPrem_SIT_KubeConfig
  - name: K8s-ServiceConnection-UAT
    value: "NKE UAT"
  - name: K8s-ServiceConnection-Prod
    value: Kubernetes_OnPrem_Prod_KubeConfig
  - name: KongEnabled
    value: true

pool: 'TIH Hosted'

stages:
  - template: 'templates/Docker Build.yml@TIH-Pipelines'
    parameters:
      ImageName: '${{variables.projectImage}}'
      DockerFile: $(Build.SourcesDirectory)/Dockerfile

  - template: 'templates/K8s Deploy - Dev.yml@TIH-Pipelines'
    parameters:
      AgentPool: $(DeployPool)
      ImageName: ${{variables.projectImage}}
      ApplicationName: '${{variables.applicationName}}'
      namespace: '${{variables.projectNamespace}}'
      K8sServiceConnection: $(K8s-ServiceConnection-Dev)
      K8sManifestDir: '${{variables.k8sManifestDir}}'
      KongEnabled: false

  - template: 'templates/K8s Deploy - SIT.yml@TIH-Pipelines'
    parameters:
      AgentPool: $(DeployPool)
      ImageName: ${{variables.projectImage}}
      ApplicationName: '${{variables.applicationName}}'
      namespace: '${{variables.projectNamespace}}'
      ACR_Service_Principal: '$(ACR_Service_Principal)'
      K8sServiceConnection: $(K8s-ServiceConnection-SIT)
      K8sManifestDir: '${{variables.k8sManifestDir}}'
      KongEnabled: false
      
  - template: 'templates/K8s Deploy - UAT.yml@TIH-Pipelines'
    parameters:
      AgentPool: $(DeployPool)
      ImageName: ${{variables.projectImage}}
      ApplicationName: '${{variables.applicationName}}'
      namespace: '${{variables.projectNamespace}}'
      ACR_Service_Principal: '$(ACR_Service_Principal)'
      K8sServiceConnection: $(K8s-ServiceConnection-UAT)
      K8sManifestDir: '${{variables.k8sManifestDir}}'
      KongEnabled: false

  - template: 'templates/K8s Deploy - Prod.yml@TIH-Pipelines'
    parameters:
      AgentPool: $(DeployPool)
      ImageName: ${{variables.projectImage}}
      ApplicationName: '${{variables.applicationName}}'
      namespace: '${{variables.projectNamespace}}'
      ACR_Service_Principal: '$(ACR_Service_Principal)'
      K8sServiceConnection: $(K8s-ServiceConnection-Prod)
      K8sManifestDir: '${{variables.k8sManifestDir}}'
      KongEnabled: false
